(ns monkeycoding.editor.codemirror
    (:require
      [cljsjs.codemirror]

      ;; plugins
      [cljsjs.codemirror.addon.scroll.simplescrollbars]
      [cljsjs.codemirror.addon.mode.simple]

      ;; languages
      [cljsjs.codemirror.mode.apl]
      [cljsjs.codemirror.mode.asn.1]
      [cljsjs.codemirror.mode.brainfuck]
      [cljsjs.codemirror.mode.clike]
      [cljsjs.codemirror.mode.clojure]
      [cljsjs.codemirror.mode.cmake]
      [cljsjs.codemirror.mode.cobol]
      [cljsjs.codemirror.mode.coffeescript]
      [cljsjs.codemirror.mode.commonlisp]
      [cljsjs.codemirror.mode.css]
      [cljsjs.codemirror.mode.d]
      [cljsjs.codemirror.mode.dart]
      [cljsjs.codemirror.mode.django]
      [cljsjs.codemirror.mode.dockerfile]
      [cljsjs.codemirror.mode.dylan]
      [cljsjs.codemirror.mode.eiffel]
      [cljsjs.codemirror.mode.elm]
      [cljsjs.codemirror.mode.erlang]
      [cljsjs.codemirror.mode.factor]
      [cljsjs.codemirror.mode.forth]
      [cljsjs.codemirror.mode.fortran]
      [cljsjs.codemirror.mode.gas]
      [cljsjs.codemirror.mode.go]
      [cljsjs.codemirror.mode.groovy]
      [cljsjs.codemirror.mode.haml]
      [cljsjs.codemirror.mode.handlebars]
      [cljsjs.codemirror.mode.haskell]
      [cljsjs.codemirror.mode.haxe]
      [cljsjs.codemirror.mode.htmlembedded]
      [cljsjs.codemirror.mode.htmlmixed]
      [cljsjs.codemirror.mode.idl]
      [cljsjs.codemirror.mode.javascript]
      [cljsjs.codemirror.mode.julia]
      [cljsjs.codemirror.mode.livescript]
      [cljsjs.codemirror.mode.lua]
      [cljsjs.codemirror.mode.markdown]
      [cljsjs.codemirror.mode.mathematica]
      [cljsjs.codemirror.mode.mllike]
      [cljsjs.codemirror.mode.modelica]
      [cljsjs.codemirror.mode.mscgen]
      [cljsjs.codemirror.mode.mumps]
      [cljsjs.codemirror.mode.nginx]
      [cljsjs.codemirror.mode.ntriples]
      [cljsjs.codemirror.mode.octave]
      [cljsjs.codemirror.mode.oz]
      [cljsjs.codemirror.mode.pascal]
      [cljsjs.codemirror.mode.pegjs]
      [cljsjs.codemirror.mode.perl]
      [cljsjs.codemirror.mode.php]
      [cljsjs.codemirror.mode.pig]
      [cljsjs.codemirror.mode.properties]
      [cljsjs.codemirror.mode.puppet]
      [cljsjs.codemirror.mode.python]
      [cljsjs.codemirror.mode.q]
      [cljsjs.codemirror.mode.r]
      [cljsjs.codemirror.mode.rpm]
      [cljsjs.codemirror.mode.rst]
      [cljsjs.codemirror.mode.ruby]
      [cljsjs.codemirror.mode.rust]
      [cljsjs.codemirror.mode.sass]
      [cljsjs.codemirror.mode.scheme]
      [cljsjs.codemirror.mode.shell]
      [cljsjs.codemirror.mode.sieve]
      [cljsjs.codemirror.mode.slim]
      [cljsjs.codemirror.mode.smalltalk]
      [cljsjs.codemirror.mode.smarty]
      [cljsjs.codemirror.mode.solr]
      [cljsjs.codemirror.mode.soy]
      [cljsjs.codemirror.mode.sparql]
      [cljsjs.codemirror.mode.spreadsheet]
      [cljsjs.codemirror.mode.sql]
      [cljsjs.codemirror.mode.stex]
      [cljsjs.codemirror.mode.stylus]
      [cljsjs.codemirror.mode.swift]
      [cljsjs.codemirror.mode.tcl]
      [cljsjs.codemirror.mode.textile]
      [cljsjs.codemirror.mode.tiddlywiki]
      [cljsjs.codemirror.mode.tiki]
      [cljsjs.codemirror.mode.toml]
      [cljsjs.codemirror.mode.tornado]
      [cljsjs.codemirror.mode.troff]
      [cljsjs.codemirror.mode.ttcn-cfg]
      [cljsjs.codemirror.mode.ttcn]
      [cljsjs.codemirror.mode.turtle]
      [cljsjs.codemirror.mode.twig]
      [cljsjs.codemirror.mode.vb]
      [cljsjs.codemirror.mode.vbscript]
      [cljsjs.codemirror.mode.velocity]
      [cljsjs.codemirror.mode.verilog]
      [cljsjs.codemirror.mode.vhdl]
      [cljsjs.codemirror.mode.vue]
      [cljsjs.codemirror.mode.xml]
      [cljsjs.codemirror.mode.yaml]
      [cljsjs.codemirror.mode.z80]))


;; config options that override everything
(def hardcoded-options {
                          "scrollbarStyle" "overlay"
                          "coverGutterNextToScrollbar" true})


(defn config->cm-options [config]
  {
    "lineNumbers" (:show-line-numbers config)
    "theme" (:theme config)
    "mode" (:language config)
    "readOnly" (:read-only config)})


(defn- create-codemirror! [dom-node config]
  (let [options (clj->js (merge (config->cm-options config) hardcoded-options))]
    (new  js/CodeMirror dom-node options)))
